import {
  AbdurRazzak,
  AfzalHossain,
  DrMostafizurRahman,
  LateTaheraAkhter,
  MdAlauddinFCMA,
  MdSahabUddin,
  MdZiaulHaqueFaruk,
  MohammadArif,
  MosaddequeHossain,
  MostafaNurmohammadPalash,
  MrKabirAhmed,
  SardinRahman,
  PranobChandraAdhikary,
  MdAsadurRahman,
  AchintoKumarNag,
} from "../assets";

export const topManagement = [
  {
    manID: 1,
    manImg: LateTaheraAkhter,
    manName: "Late Tahera Akhter",
    manDesignation: "Chairman",
  },
  {
    manID: 2,
    manImg: DrMostafizurRahman,
    manName: "Dr. Mostafizur Rahman",
    manDesignation: "Managing Director",
  },
  {
    manID: 3,
    manImg: SardinRahman,
    manName: "Sardin Rahman",
    manDesignation: "Deputy Managing Director",
  },
  {
    manID: 4,
    manImg: AfzalHossain,
    manName: "Afzal Hossain",
    manDesignation: "Advisor, Marketing",
  },
  {
    manID: 5,
    manImg: MosaddequeHossain,
    manName: "Mosaddeque Hossain",
    manDesignation: "General Manager, Customer Services",
  },
  {
    manID: 6,
    manImg: MdAlauddinFCMA,
    manName: "Md Alauddin, FCMA",
    manDesignation: "DGM & Head of Finance & Accounts",
  },
  {
    manID: 7,
    manImg: AchintoKumarNag,
    manName: "Achinto Kumar Nag",
    manDesignation: "DGM (HR & Admin)",
  },
  {
    manID: 8,
    manImg: MostafaNurmohammadPalash,
    manName: "Mostafa Nurmohammad (Palash)",
    manDesignation: "AGM, (Engineering)",
  },
  {
    manID: 9,
    manImg: AbdurRazzak,
    manName: "Abdur Razzak",
    manDesignation: "AGM, (Finance & Accounts)",
  },
  {
    manID: 10,
    manImg: MohammadArif,
    manName: "Mohammad Arif",
    manDesignation: "Manager, (ICT)",
  },
  {
    manID: 11,
    manImg: MdZiaulHaqueFaruk,
    manName: "Md Ziaul Haque Faruk",
    manDesignation: "Manager, (Marketing)",
  },
  {
    manID: 12,
    manImg: MrKabirAhmed,
    manName: "Mr Kabir Ahmed",
    manDesignation: "Manager, (Engineering)",
  },
  {
    manID: 13,
    manImg: MdAsadurRahman,
    manName: "MD. ASADUR RAHMAN",
    manDesignation: "Manager, Laboratory",
  },
  {
    manID: 14,
    manImg: MdSahabUddin,
    manName: "Md Sahab Uddin",
    manDesignation: "Manager, (Finance & Accounts)",
  },
  {
    manID: 15,
    manImg: PranobChandraAdhikary,
    manName: "Pranob Chandra Adhikary",
    manDesignation: "Quality Manager",
  },
];
